### ISSUE TITLE
Don't trigger j/k shortcuts if typing an email

### ISSUE THREAD

**Issue by tmcw** [tmcw/flair#40]
Hopefully there's a way to preventdefault on that input field, to fix this bug. Initially reported at https://twitter.com/johanbrook/status/1244380002457718785

**Comment by jasikpark** [comment]
oof yes, i experienced this when typing in my email hosted on jasik.xyz

**Comment by tmcw** [comment]
sorry about that! would have noticed this bug if my email included j or k :) fix incoming in a few moments.

**Comment by jasikpark** [comment]
<div></div><div>sorry about that! would have noticed this bug if my email included j or k :) fix incoming in a few moments.
<br/>
<br/>-- 
<br/>You are receiving this because you commented.
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/tmcw/flair/issues/40#issuecomment-605783911</div>
