### ISSUE TITLE
Equate Whiskey is a crime

### ISSUE THREAD

**Issue by mjmdavis** [tmcw/flair#6]

**Comment by wooorm** [comment]
🤷‍♂️ There’s an option you can use to turn that on or off: if it’s a crime, then don’t equate! I’d also say that’s it’s a feature that you can swap ingredients in cocktails to make new ones, not a bug 😉

**Comment by mjmdavis** [comment]
Whiskey is anything made from fermented grain mash. There are many types of whiskey, often very different in flavour, ingredients, and processing. For cocktails, the critical point is that there is a huge difference in flavour between these types and classes.

Below I present a selection of evidence that changing the whisky changes the drink:

A good example of this is the _Collins_. This cocktail has many variations with different names depending on the spirit chosen. [Diffords highlights several versions](https://www.diffordsguide.com/encyclopedia/490/cocktails/collins-cocktails-recipes-and-history) with different types of whisky:

* Captain Collins - Canadian whisky
* Colonel Collins - bourbon whisky
* Sandy Collins - Scotch whisky
* Mike Collins - Irish whisky

Cocktail recipes differentiate between whiskies. [IBA](https://iba-world.com/iba-cocktails/) and [Diffords](https://www.diffordsguide.com/cocktails/search-by-ingredients), the two canonical sources of cocktail recipes clearly draw a line between different types of whisky.

In fact, a strong argument can be made that rum is less diverse than whisky. So why not equate rum? Putting dark rum in a recipe that specifies light rum will change a drink less than substituting rye for scotch.

Why treat whisky, the most popular and diverse spirit as one single type of drink but not do the same to Vodka, Rum, etc...

That said the app now has a pedantic mode which I feel does an equal disservice to all of the large classes of spirit. This seems much more fair 🤪.

**Comment by wooorm** [comment]
While you are totally right, I would say that the equating you’re doing in your list of Collins’s is a perfect example of why equating makes lovely libations, and as a float on top I would like to add that the John and Tom Collins (both based in gin) were the originals, and therefore Whiskey is equated for Gin!

Note that oldfasioned.tech currently does list the original recipes, whether you’re in pedantic mode or not. I’m personally more in favour of creativity and inventing things, instead of being able to follow recipes to the letter. In normal-people-mode, you’re just allowed to make more drinks. No harm in that?! 🍸
